{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.slprime",
    "module": "ChromaticTooltips",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.12-dev.jar",
          "url": "ChromaticTooltips-1.0.12-dev.jar",
          "size": 226509,
          "sha512": "90c5e5060b55df7aa13882b39aafded6495f2eb0e545a4357de8419ea02c62f9c1547d5d18cb9aaf9ef56cfcabd37b8bda8f98e784d01b9e195de0d44bcbc871",
          "sha256": "df9e499bd421c14dd9a134e57f7994fad3bc11fd31abffecd99ed893c248310f",
          "sha1": "042a4a7bc20b1667903c0c0970812b01145939af",
          "md5": "85b761e7b6063399744c2747f9cc93e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.23"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.9.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.8.41"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ChromaticTooltips-1.0.12-dev.jar",
          "url": "ChromaticTooltips-1.0.12-dev.jar",
          "size": 226509,
          "sha512": "90c5e5060b55df7aa13882b39aafded6495f2eb0e545a4357de8419ea02c62f9c1547d5d18cb9aaf9ef56cfcabd37b8bda8f98e784d01b9e195de0d44bcbc871",
          "sha256": "df9e499bd421c14dd9a134e57f7994fad3bc11fd31abffecd99ed893c248310f",
          "sha1": "042a4a7bc20b1667903c0c0970812b01145939af",
          "md5": "85b761e7b6063399744c2747f9cc93e2"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.12.jar",
          "url": "ChromaticTooltips-1.0.12.jar",
          "size": 228419,
          "sha512": "6683d321e4c579728dafd05eadcdb216bc72262643e7a0eb40ac7c3a77890105e7a817861e0a5995617c6b77b456abeca8dffb29aaa3c0bfdb4e42beaf93b02c",
          "sha256": "d8f8a7247fe5749404148648634cf142372704c83c273de9f4ee294fde13cc2f",
          "sha1": "9d50cb4588752dec68d82a153f5a0a012dbcdfa8",
          "md5": "b9a64798efd43126e64e003332003b09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.12-sources.jar",
          "url": "ChromaticTooltips-1.0.12-sources.jar",
          "size": 126256,
          "sha512": "b9fd46543ae5250af144b188f63a956d837e937af32692743291e130a24355be002725b560a52962f8fa05d1d4af8d59b271ecb56d8d89776984099bb339ff80",
          "sha256": "525bde420e535da3fdfa5a583c84648926d298fc54d3cd6b0035d40caf394905",
          "sha1": "c460d130d1993d8a53eb4305442077d983acc566",
          "md5": "ac7d6f9d8a2c53c708ac036fdc62024f"
        }
      ]
    }
  ]
}
